version: '2.2'
services: 
  ######################################################### MongoDB #########################################################
  mongo:
    image: mongo:4.4.0-bionic
    container_name: 'osquery-file-carve-mongo'
    restart: unless-stopped
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
    volumes:  
      - file-carve-mongo:/data/db
    ports:
      - 27017:27017
    networks: 
      - default
      - file-carve-backend

networks:
  kolide-backend:
  file-carve-backend:

volumes: 
  kolide-logs:
  kolide-redis:
  kolide-mysql:
  file-carve-mongo: