FROM nginx:1.19.2-alpine

RUN mkdir /etc/nginx/tls
COPY conf/nginx/tls/*.crt /etc/nginx/tls/kolide.crt
COPY conf/nginx/tls/*.key /etc/nginx/tls/kolide.key

COPY conf/nginx/nginx.conf /etc/nginx/nginx.conf
COPY conf/nginx/kolide.conf /etc/nginx/conf.d/kolide.conf