FROM nginx:1.17.8-alpine

RUN mkdir /etc/nginx/tls
COPY conf/tls/kolide/*.crt /etc/nginx/tls/kolide.crt
COPY conf/tls/kolide/*.key /etc/nginx/tls/kolide.key

COPY conf/nginx/nginx.conf /etc/nginx/nginx.conf
COPY conf/nginx/kolide-NO_MUTUAL_TLS.conf /etc/nginx/conf.d/kolide.conf